apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "cloki"
spec:
  configuration:
    clusters:
      - name: "cloki"
        layout:
          shardsCount: 1
          replicasCount: 1
    settings:
      #http_port: 8124
      #tcp_port: 9001
      #interserver_http_port: 9010
      compression/case/method: zstd
      disable_internal_dns_cache: 1
  defaults:
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
      serviceTemplate: svc-template

  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.4
              ports:
                - name: http
                  containerPort: 8123
                - name: tcp
                  containerPort: 9000
                - name: interserver
                  containerPort: 9010
              #volumeMounts:
              #  - name: bootstrap-configmap-volume
              #    mountPath: /docker-entrypoint-initdb.d
              resources:
                requests:
                  memory: 4Gi
                  cpu: 2
                limits:
                  memory: 8Gi
                  cpu: 2
          #volumes:
          #  - name: bootstrap-configmap-volume
          #    configMap:
          #      name: bootstrap-mounted-configmap
          

    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          storageClassName: "managed-csi-premium"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
      - name: log-volume-template
        spec:
          storageClassName: "managed-csi-premium"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi

    serviceTemplates:
      - name: svc-template
        generateName: chendpoint-{chi}
        metadata:
          #labels:
          #  custom.label: "custom.value"
          annotations:
            #cloud.google.com/load-balancer-type: "Internal"
            #service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
            #service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            #service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
            #service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          #type: LoadBalancer
          type: ClusterIP
