apiVersion: v1
kind: Service
metadata:
  annotations:
    cloki.cmd: cloki.org
  labels:
    io.kompose.service: cloki
  name: cloki
spec:
  ports:
    - name: "3100"
      port: 3100
      targetPort: 3100
  selector:
    io.kompose.service: cloki

