---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-clickhouse
  namespace: observability
data:
  config.yaml: |
    address: tcp://chendpoint-jaeger.observability:9000
    database: jaeger
    username: clickhouse_operator
    password: clickhouse_operator_password
    ttl: 7
    spans_table:
    spans_index_table:
    operations_table:
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: production
  query:
    options:
      prometheus:
        # thanos
        server-url: "http://thanos-query.observability:9090"
        # promscale
        #server-url: http://tobs-promscale-connector.observability:9201
    metricsStorage:
      type: prometheus
  storage:
    type: grpc-plugin
    grpcPlugin:
      image: ghcr.io/jaegertracing/jaeger-clickhouse:0.9.0
    options:
      grpc-storage-plugin:
        binary: /plugin/jaeger-clickhouse
        configuration-file: /plugin-config/config.yaml
        #log-level: debug
  collector:
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 128Mi
  volumeMounts:
    - name: plugin-config
      mountPath: /plugin-config
  volumes:
    - name: plugin-config
      configMap:
        name: jaeger-clickhouse
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.dev.metatron.app/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.dev.metatron.app/oauth2/start?rd=$scheme://$best_http_host$request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    hosts:
      - jaeger.dev.metatron.app
    tls:
      - hosts:
          - jaeger.dev.metatron.app
        secretName: grandview-dev-tls