{
 "title": "Flink Dashboard",
 "description": "修改单体指标",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DBSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "taskmanagers",
   "type": "stat",
   "description": "任务管理器的数量",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_numRegisteredTaskManagers)by(host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "taskSlotsTotal",
   "type": "stat",
   "description": "任务槽的总数",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_taskSlotsTotal)by(host)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "taskSlotsAvailable",
   "type": "stat",
   "description": "可用任务槽的数量",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_taskSlotsAvailable)by(host)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "numRunningJobs",
   "type": "stat",
   "description": "正在运行的作业数",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_numRunningJobs)by(host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Job USES head %",
   "type": "graph",
   "description": "Job使用head的百分比",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_jobmanager_Status_JVM_Memory_Heap_Used/flink_jobmanager_Status_JVM_Memory_Heap_Max)by(host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU of TaskManger",
   "type": "graph",
   "description": "JVM的最近CPU使用率 Task\n",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_Status_JVM_CPU_Load)by(host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU of JobManger",
   "type": "graph",
   "description": "JVM的最近CPU使用率\n",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(flink_jobmanager_Status_JVM_CPU_Load)by(host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Task USES head %",
   "type": "graph",
   "description": "Task 使用head的百分比",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Used/flink_taskmanager_Status_JVM_Memory_Heap_Max) by(host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Job Manger threads",
   "type": "graph",
   "description": "The total number of live threads.\t",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Task Manger threads",
   "type": "timeseries",
   "description": "The total number of live threads.\t",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count{}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}