apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query-tobs
  namespace: observability
  labels:
    app: jaeger-query-tobs
    component: jaeger-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-query-tobs
      component: jaeger-query
  template:
    metadata:
      labels:
        app: jaeger-query-tobs
        component: jaeger-query
    spec:
      containers:
        - image: jaegertracing/jaeger-query:1.33
          imagePullPolicy: IfNotPresent
          name: jaeger
          args:
              - --grpc-storage.server=tobs-promscale-connector.observability.svc.cluster.local:9202
              - --grpc-storage.tls.enabled=false
              - --grpc-storage.connection-timeout=1h
          ports:
            - containerPort: 16686
              name: jaeger-ui
          env:
            - name: SPAN_STORAGE_TYPE
              value: grpc-plugin
            # SPM
            # https://www.jaegertracing.io/docs/1.33/spm/
            - name: METRICS_STORAGE_TYPE
              value: "prometheus"
            - name: PROMETHEUS_SERVER_URL
              value: "http://tobs-promscale-connector.observability:9201"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-tobs
  namespace: observability
  labels:
    app: jaeger-query
spec:
  selector:
    app: jaeger-query-tobs
    component: jaeger-query
  type: ClusterIP
  ports:
  - name: jaeger
    port: 16686
    targetPort: 16686
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.dev.metatron.app/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.dev.metatron.app/oauth2/start?rd=$scheme://$best_http_host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  name: jaeger-query-tobs-external
  namespace: observability
spec:
  rules:
    - host: jaeger.dev.metatron.app
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/"
            backend:
              service:
                name: jaeger-query-tobs
                port:
                  number: 16686
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - jaeger.dev.metatron.app
      secretName: grandview-dev-tls